### ISSUE TITLE
Office hours inconsistent

### ISSUE THREAD

**Issue by gregordecristoforo** [uit-no/hpc.uit.no#29]
The times at https://github.com/uit-no/hpc.uit.no/blob/594400e1053364ae9489d82a3ee9e20cfd98f901/content/_index.md?plain=1#L48
are inconsistent with 
https://github.com/uit-no/hpc.uit.no/blob/594400e1053364ae9489d82a3ee9e20cfd98f901/content/_index.md?plain=1#L51

The [RSE website](https://research-software.uit.no/) also states 13:00-15:00. Which times are correct?

**Comment by Danzelot** [comment]
Thanks for noticing. That happens when you do copy and paste and forget to read it again.
