### ISSUE TITLE
Clean up header sections

### ISSUE THREAD

**Issue by Danzelot** [uit-no/hpc.uit.no#42]
In my opinion we have too many sections linked in the header which makes it easy to loose the overview.

I have three suggestions:

1. Merge "Team" and "About us" section. 
2. Remove the "NRIS" one as it is a link out of our page which always feels very disruptive. We already have a link to the NRIS docs in the footer
3. "Accounts" is not very descriptive and should called "Getting started" instead.

What do you think?

**Comment by bast** [comment]
Yes, yes, and yes :-)
